title:   '{curlybracket}'
author:
  name:  'Ben Pye'

front_limit: 5
disqus_shortname: 'curlybracket'
analytics_id: 'UA-67260324-1'

path:    ''
url:     'https://curlybracket.co.uk'
baseurl: ''

markdown:   redcarpet

sass:
  style:    expanded

permalink:  /:title/

exclude:    [vendor]
