title:   '{curlybracket}'
author:
  name:  'Ben Pye'

front_limit: 5
disqus_shortname: 'curlybracket'
analytics_id: 'UA-67260324-1'

path:    ''
url:     'https://curlybracket.co.uk'
baseurl: ''

markdown:   redcarpet

sass:
  style:    expanded

permalink:  /:title/

exclude:    ['README.md', 'config.ru', 'Gemfile', 'Gemfile.lock', 'vendor']

gems:
  - jekyll-auto-image
  - jekyll-minimagick

mini_magick:
  thumbnail:
    source: images/original
    destination: images/thumbnail
    resize: "200x200"
  hero:
    source: images/original
    destination: images/hero
    resize: "768x768"
